### PR TITLE
refactor: (WIP) dependancy injection, stragy pattern

### PR DESCRIPTION
**Pull request by arthurgustin**
Hello,
I've worked on the code base.
Summary:
   - Dependancy injection on the main function
   - Strategy pattern for each linter (only compute, not render)
   - Fixed some test

I'm quite confident with the way linters compute are handled. I didn't touch the html generation part and maybe there is something to do. I want to avoid this:
```
// convert all linter's data.
	htmlData.converterUnitTest(*r)
	htmlData.converterCopy(*r)
	htmlData.converterCyclo(*r)
	htmlData.converterDepth(*r)
	htmlData.converterInterfacer(*r)
	htmlData.converterSimple(*r)
	htmlData.converterSpell(*r)
	htmlData.converterCount(*r)
	htmlData.converterDead(*r)
	htmlData.converterDependGraph(*r)
```
I have to think about the best way to fill the html template

Also I deleted the package tool, because in my opinion it's the reporter responsability to generate the different outputs.

What do you think ?

### CODE REVIEW

**Comment by wgliang** [comment]
wonderfu!
This is a good job.

**Comment by wgliang** [comment]
But I think linters's initialization,inject.Populate() and reporter.AddLinters() should be removed into package engine, It's not the main.go should do.

So what do you think of it?

**Comment by arthurgustin** [comment]
It's common in go to see this pattern in the main function. In the end we have a big main function (or you can use init() that is called by default) and the code inside packages does not need to manage it's own dependancies.
I didn't expect you merged the code so fast but ok !
Do you mind if I continue to refactor the template generation part ?

**Comment by arthurgustin** [comment]
I tagged the commit with (WIP) for work in progress, maybe you should rename it

**Comment by wgliang** [comment]
sure, you can refactor the template generation part.I think I can learn more from your code.

**Pull request merged**
